small_joint:
  mass: 1.326 # mass in kg
  height: 0.2 # height in meters
  radius: 0.08 # radius of joint in meters
  bellows_radius: 0.04 # radius to center of bellows in meters
  bend_limit: 110 # bend limit in degrees, probably needs to be lengths of tendons
  lumped_stiffness: 30 # lumped stiffness of the joint in Nm/rad, is divided evenly between bellows
  lumped_damping: 7.5 # lumped damping of the joint in Nm/(rad/s), is divided evenly between universal joint in series

medium_joint:
  mass: 1.326 # mass in kg
  height: 0.2 # height in meters
  radius: 0.1 # radius of joint in meters
  bellows_radius: 0.06 # radius to center of bellows in meters
  bend_limit: 110 # bend limit in degrees, probably needs to be lengths of tendons
  lumped_stiffness: 30 # lumped stiffness of the joint in Nm/rad, is divided evenly between bellows
  lumped_damping: 15 # lumped damping of the joint in Nm/(rad/s), is divided evenly between universal joint in series

large_joint:
  mass: 2.653 # mass in kg
  height: 0.2 # height in meters
  radius: 0.125 # radius of joint in meters
  bellows_radius: 0.075 # radius to center of bellows in meters
  bend_limit: 90 # bend limit in degrees, probably needs to be lengths of tendons
  lumped_stiffness: 135 # lumped stiffness of the joint in Nm/rad, is divided evenly between bellows
  lumped_damping: 7.5 # lumped damping of the joint in Nm/(rad/s), is divided evenly between universal joint in series
